# Generated by Django 5.1.5 on 2025-02-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название заголовка', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Введите текст статьи', null=True, verbose_name='Содержание статьи')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='blog_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания поста', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения продукта', verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
